Dev
SonicCloudOrg/sonic-server pull request #194
Opened 2022-05-24 03:17 UTC by dongyi0412

增加：
公共步骤：复制功能，搜索步骤
控件元素：复制功能

2022-05-24 03:57 UTC, ZhouYixun commented
@JayWenStar WDYT

2022-05-24 03:58 UTC, ZhouYixun commented
> 增加： 公共步骤：复制功能，搜索步骤 控件元素：复制功能

i18n其他文件你也先同步一下，百度翻译就好了

2022-05-25 04:43 UTC, ZhouYixun reviewed
viewed.

2022-05-25 04:48 UTC, JayWenStar commented
感谢您的PR，预计今晚会pull下来测试+review，请耐心等候

2022-05-25 05:43 UTC, JayWenStar commented
光看了下代码，还没测试功能，先提两个小问题吧：
1. 注入Bean比较多的情况下还是用回紧凑格式
![image](https://user-images.githubusercontent.com/94054171/170188328-b08ac33d-b8d4-45f8-b92e-448cb5ea4164.png)
2. sql操作尽量使用函数式接口，现在手写全字段，在表改动之后很容易遗漏

2022-05-25 08:26 UTC, dongyi0412 commented
@JayWenStar  注入Bean问题 主要是我后面使用了idea 代码重构功能，后面没仔细看；全字段写入只有写复制功能有这样写，如果是复制这样的功能，不可避免需要全字段插入；如果是这样即使使用了函数式接口，是否也需要更改，说的遗漏是 改表字段以后忘记修改这个注入的sql吗？

2022-05-25 10:53 UTC, JayWenStar commented
> @JayWenStar 注入Bean问题 主要是我后面使用了idea 代码重构功能，后面没仔细看；全字段写入只有写复制功能有这样写，如果是复制这样的功能，不可避免需要全字段插入；如果是这样即使使用了函数式接口，是否也需要更改，说的遗漏是 改表字段以后忘记修改这个注入的sql吗？

1. 那我理解第一个问题是可以改了
2. 函数式没改就会直接报错，这么说应该懂了吧

2022-05-25 13:47 UTC, JayWenStar requested changes

2022-05-25 13:47 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/services/impl/TestCasesServiceImpl.java
> +    @Autowired
这里注入比较多的话，还是改回紧凑的格式吧，光这些就占一个屏，再加几个就要翻页了

2022-05-25 13:47 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsStepsMapper.java
> +    Integer InsertPublicStepsSteps(@Param("public_steps_id")Integer publicStepsId, @Param("steps_id")Integer stepsId);
像这种单表非必要sql函数的crud还是用函数式，方便之后改了字段能快速check问题，看了下很多地方都是这种问题

2022-05-25 13:47 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/services/impl/PublicStepsServiceImpl.java
> +        //用for循环 插入公共步骤和子步骤
这里少了递归的逻辑

2022-05-25 13:47 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/services/impl/TestCasesServiceImpl.java
> +    public boolean copyTestById(int id) {
这里也是没有递归的逻辑

2022-05-25 13:49 UTC, JayWenStar requested changes

2022-05-25 13:49 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/TestCasesMapper.java
> +    @Update("UPDATE test_cases set name='${name}_copy',edit_time=NOW() WHERE id =${id} ")
直接用mybatis插件更新时间即可

2022-05-25 13:50 UTC, JayWenStar requested changes

2022-05-25 13:50 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/StepsMapper.java
> +    @Select("select * FROM steps WHERE  content = '' AND case_id = ${id}")
只是统计数量的话，可以用`count(*)`或者`count(1)`替代，没必要用*

2022-05-25 13:54 UTC, JayWenStar commented
比较大的问题在于复制用例步骤相关的逻辑时，没有递归遍历层级关系

2022-05-25 13:57 UTC, dongyi0412 commented
好的，我多看看。感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月25日(星期三) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [SonicCloudOrg/sonic-server] 复制功能 (PR #194)





 
比较大的问题在于复制用例步骤相关的逻辑时，没有递归遍历层级关系
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

2022-05-26 11:17 UTC, closed without merging