增加： 公共步骤：复制功能，搜索步骤 控件元素：复制功能 测试用例：复制功能]
SonicCloudOrg/sonic-server pull request #195
Opened 2022-05-26 11:20 UTC by dongyi0412

重写代码。

2022-05-26 11:23 UTC, dongyi0412 commented
@zhou
@JayWenStar 全部重写了，请看下还有其它问题吗？

2022-05-26 12:43 UTC, JayWenStar commented
你是不是之前pr的评论没看完，步骤没有递归处理

2022-05-26 12:48 UTC, JayWenStar requested changes

2022-05-26 12:48 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsMapper.java
>      @Select("select id,name from public_steps where project_id=#{projectId} and platform=#{platform} order by id desc")
这个单表也能改成函数式

2022-05-26 13:01 UTC, dongyi0412 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsMapper.java
>      @Select("select id,name from public_steps where project_id=#{projectId} and platform=#{platform} order by id desc")
好的，大佬，我再去看看。麻烦了。

2022-05-26 13:02 UTC, JayWenStar commented
还有疑惑的点是，在什么情况下你会用到复制控件的接口？这个需求看起来是不太成立的

2022-05-26 13:05 UTC, ZhouYixun commented
> @zhou @JayWenStar 全部重写了，请看下问题吗？

你这是不是艾特错人了

2022-05-27 08:50 UTC, dongyi0412 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsMapper.java
>      @Select("select id,name from public_steps where project_id=#{projectId} and platform=#{platform} order by id desc")
大佬，我本地部署服务以后，测试了复制的功能；包括：公共步骤，if，elif，普通步骤等基本所有功能。 发现都是正常的 测试用例都是跑的通。 递归的写法主要是代码层的优化吗？

2022-05-27 09:04 UTC, dongyi0412 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsMapper.java
>      @Select("select id,name from public_steps where project_id=#{projectId} and platform=#{platform} order by id desc")
大佬，我自己部署全部流程写了用例进行测试，功能方面都是对的（包括if. elif.普通步骤,公共步骤）等； 请问 递归的话主要是对代码的优化吗？

2022-05-27 10:50 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsMapper.java
>      @Select("select id,name from public_steps where project_id=#{projectId} and platform=#{platform} order by id desc")
> 大佬，我自己部署全部流程写了用例进行测试，功能方面都是对的（包括if. elif.普通步骤,公共步骤）等； 请问 递归的话主要是对代码的优化吗？

你确定你真的有测试吗。。我所有旧的测试case都报这个错
![image](https://user-images.githubusercontent.com/94054171/170685707-ce20892c-ced4-4b29-805c-73063d628545.png)

2022-05-27 14:20 UTC, dongyi0412 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsMapper.java
>      @Select("select id,name from public_steps where project_id=#{projectId} and platform=#{platform} order by id desc")
![image](https://user-images.githubusercontent.com/84267690/170717597-5f884cde-72b3-4d10-b1af-4e454ec4bb31.png)
![image](https://user-images.githubusercontent.com/84267690/170717619-2d7087c6-1f88-4624-bfc3-b1525742e4a6.png)下午我确实有进行测试，测试数据是我们公司数据库copy本地进行测试。这个报在重构过程中遇到过，当时处理了这种情况，我现在再去考虑下为什么旧的case会出现这种情况。我会着重考虑下这种情况。不好意思，添麻烦了。

2022-05-27 15:13 UTC, JayWenStar commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsMapper.java
>      @Select("select id,name from public_steps where project_id=#{projectId} and platform=#{platform} order by id desc")
> ![image](https://user-images.githubusercontent.com/84267690/170717597-5f884cde-72b3-4d10-b1af-4e454ec4bb31.png) ![image](https://user-images.githubusercontent.com/84267690/170717619-2d7087c6-1f88-4624-bfc3-b1525742e4a6.png)下午我确实有进行测试，测试数据是我们公司数据库copy本地进行测试。这个报在重构过程中遇到过，当时处理了这种情况，我现在再去考虑下为什么旧的case会出现这种情况。我会着重考虑下这种情况。不好意思，添麻烦了。

你是不是没push代码，我现在随便创建一个用例，添加一个步骤，复制都失败

2022-05-27 15:31 UTC, JayWenStar commented
我试着把你越界的bug修复了，然后问题就像之前说的，没有处理层级关系（感觉你是不是忘记push代码了？）
![image](https://user-images.githubusercontent.com/94054171/170731166-ff16ff35-2f67-4ff4-9a50-8835c296e245.png)
![image](https://user-images.githubusercontent.com/94054171/170731238-eb0d2e54-ff1f-4976-9886-52bef53e33a6.png)

2022-05-27 15:37 UTC, dongyi0412 commented
我在起服务重新测试。很抱歉这么晚还给你添麻烦。我继续全部重新进程测试。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 晚上11:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SonicCloudOrg/sonic-server] 增加： 公共步骤：复制功能，搜索步骤 控件元素：复制功能 测试用例：复制功能] (PR #195)





 
我试着把你越界的bug修复了，然后问题就像之前说的，没有处理层级关系（感觉你是不是忘记push代码了？）
 
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-05-27 15:46 UTC, JayWenStar commented
> 我在起服务重新测试。很抱歉这么晚还给你添麻烦。我继续全部重新进程测试。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月27日(星期五) 晚上11:31 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [SonicCloudOrg/sonic-server] 增加： 公共步骤：复制功能，搜索步骤 控件元素：复制功能 测试用例：复制功能] (PR #195) 我试着把你越界的bug修复了，然后问题就像之前说的，没有处理层级关系（感觉你是不是忘记push代码了？） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没关系，我是晚上下班才有时间看，夜猫子

2022-05-27 17:39 UTC, dongyi0412 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/mapper/PublicStepsMapper.java
>      @Select("select id,name from public_steps where project_id=#{projectId} and platform=#{platform} order by id desc")
我找到了问题所在， 在查到原来的步骤以后，我修改了他所属的caseid ，但是没有处理parent_id 字段，parent_id字段应该是要关联新插入的父级。。我明天尝试解决他。我试试，handleStep 之类的方法 。😁

2022-06-07 06:20 UTC, dongyi0412 commented
@JayWenStar 测试用例复制功能，我尝试了很久以后暂停了。子步骤都递归拿出来了，在步骤关联id上有问题。代码已经注视，其他功能都没有问题； 公共步骤的复制 只需要管理步骤，不需要复制步骤，所以不需要递归关联子步骤。

2022-06-07 07:04 UTC, closed without merging