fix:公共步骤复制steps关联问题。
SonicCloudOrg/sonic-server pull request #240
Opened 2022-08-15 09:07 UTC by dongyi0412

修复了公共步骤bug，不小心提交了配置文件。

2022-08-15 09:11 UTC, ZhouYixun commented
env文件先还原一下

2022-08-15 09:11 UTC, ZhouYixun requested changes
先还原env文件

2022-08-21 03:51 UTC, ZhouYixun commented
公共步骤复制关联的问题我和 @yaming116 讨论了下，感觉还是以前的逻辑就行了，修改子步骤应该所有都生效才对

2022-08-22 12:55 UTC, ZhouYixun reviewed
需要再调整

2022-08-23 12:03 UTC, dongyi0412 commented
@yaming116  老大，review一下，公共步骤代码在前端隐藏掉了。review以下步骤复制和用例复制

2022-08-23 15:41 UTC, ZhouYixun commented
> @yaming116 老大，review一下，公共步骤代码在前端隐藏掉了。review以下步骤复制和用例复制

前端的隐藏记得commit一下

2022-08-25 02:50 UTC, ZhouYixun approved these changes
合入测试

2022-08-25 02:50 UTC, merged