后端服务添加slack机器人：https://sonic-cloud.wiki/d/2566-slack
SonicCloudOrg/sonic-server pull request #313
Opened 2023-02-15 04:14 UTC by stephenwang1011

> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [ ] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [ ] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [ ] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [ ] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### Description

2023-02-15 05:20 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +                "通  过  率：" + (total > 0 ?
通过率怎么多了几个空格

2023-02-15 05:20 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +                "一共测试：" + count + "次" + "\n" +
同上

2023-02-15 05:20 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +                "通  过  率：" + (total > 0 ?
同上

2023-02-15 05:22 UTC, ZhouYixun commented
pr不规范，标题以标题为fix、feat或doc开头。

并且你的pr信息的复选框保存后没勾选

2023-02-15 05:23 UTC, ZhouYixun commented
引用的超链接不应该放标题，而是放Description下面

2023-02-15 05:24 UTC, stephenwang1011 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +                "通  过  率：" + (total > 0 ?
主要是为了让输出的内容对齐了
![image](https://user-images.githubusercontent.com/3350356/218940131-01062e88-4201-4934-bb18-dad2ce4f0586.png)


> 通过率怎么多了几个空格

2023-02-15 05:24 UTC, stephenwang1011 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +                "通  过  率：" + (total > 0 ?
你看下实际效果图 主要是为了达到这个对齐效果
![image](https://user-images.githubusercontent.com/3350356/218940237-cf8e935f-8d44-4a4c-b314-c48a13cb0c43.png)
****

2023-02-15 05:26 UTC, ZhouYixun requested changes
整体文案为什么不跟其他机器人统一，而是这里又单独的，这样不合理。后面报告通知我们也会做成国际化的，暂时你先更改吧

2023-02-15 05:27 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +                "通  过  率：" + (total > 0 ?
> 你看下实际效果图 主要是为了达到这个对齐效果 ![image](https://user-images.githubusercontent.com/3350356/218940237-cf8e935f-8d44-4a4c-b314-c48a13cb0c43.png)

如果是为了这个，后面我们国际化还有不同翻译的，肯定对不准的，我觉得可以不用太纠结这个？

2023-02-15 05:28 UTC, stephenwang1011 commented
> 整体文案为什么不跟其他机器人统一，而是这里又单独的，这样不合理。后面报告通知我们也会做成国际化的，暂时你先更改吧

好 那我更改一下 和大家保持一样的文案

2023-02-15 05:30 UTC, stephenwang1011 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +                "通  过  率：" + (total > 0 ?
嗯 我改下  保持统一，之前没考虑的 国际化的问题

2023-02-15 05:34 UTC, ZhouYixun commented
![image](https://user-images.githubusercontent.com/56339314/218941547-2d71c04e-f639-4268-87f6-39aafd252c18.png)

不知道你明不明白我的意思

2023-02-15 05:36 UTC, stephenwang1011 commented
> ![image](https://user-images.githubusercontent.com/56339314/218941547-2d71c04e-f639-4268-87f6-39aafd252c18.png)
> 
> 不知道你明不明白我的意思

明白 大佬

2023-02-15 06:25 UTC, stephenwang1011 commented
前后端都已经修改 @ZhouYixun

2023-02-15 09:21 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +        Map<Object, Object> slackMap = new LinkedHashMap<>();
这里可以直接用JSONObject

2023-02-15 09:24 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +        Map<Object, Object> slackMap = new LinkedHashMap<>();
不过你这么处理也不是不行

2023-02-15 09:24 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +    static class SlackMessage {
static是不是可以去掉

2023-02-15 09:25 UTC, ZhouYixun requested changes
再看一下

2023-02-15 09:29 UTC, stephenwang1011 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +    static class SlackMessage {
这个我是按照idea提示加上去的

2023-02-15 09:29 UTC, ZhouYixun commented
根据开个class存放数据不是不行，但是后续如果某些通知有新增字段，感觉不如直接维护JSONObject好点

2023-02-15 09:34 UTC, stephenwang1011 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +        Map<Object, Object> slackMap = new LinkedHashMap<>();
那我暂时不处理吧 如果你坚持的话 我可以测试一下。
以下是 slack发消息的一个模板
`{
  "text":"这里是通知title",
 "blocks": [
  {
   "type": "section",
   "text": {
    "type": "mrkdwn",
    "text": "*Sonic云真机测试平台日报* \n项目名称：这里是名称\n测试时间：这里是时间\n通过条数：这里是通过\n异常条数：这里是异常\n失败条数：这里是失败\n通  过  率：这里是通过率\n详        情：这里是详情"
   }
  }
 ]
}`

2023-02-15 09:36 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +    static class SlackMessage {
行吧，后续再维护，你单测跑了能发是吗？

2023-02-15 09:40 UTC, stephenwang1011 commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/tools/robot/vendor/SlackNotifyImpl.java
> +    static class SlackMessage {
是的 可以发的 可以看看 截图 测试无误
![image](https://user-images.githubusercontent.com/3350356/218990868-9df5a5c1-8ef8-4763-bb77-3a5506cca548.png)

2023-02-15 09:41 UTC, stephenwang1011 commented
> 根据开个class存放数据不是不行，但是后续如果某些通知有新增字段，感觉不如直接维护JSONObject好点

你看还需要改哪些  我可以在研究下 直接指明一下 哈哈哈

2023-02-15 09:50 UTC, ZhouYixun commented
> > 根据开个class存放数据不是不行，但是后续如果某些通知有新增字段，感觉不如直接维护JSONObject好点
> 
> 你看还需要改哪些 我可以在研究下 直接指明一下 哈哈哈

没有了，方便的话可以补充下文档 https://github.com/SonicCloudOrg/sonic-offical-website/edit/main/src/doc/doc-robot.md

2023-02-15 09:51 UTC, ZhouYixun approved these changes
合入

2023-02-15 09:51 UTC, merged

2023-02-15 09:59 UTC, stephenwang1011 commented
> > > 根据开个class存放数据不是不行，但是后续如果某些通知有新增字段，感觉不如直接维护JSONObject好点
> > 
> > 
> > 你看还需要改哪些 我可以在研究下 直接指明一下 哈哈哈
> 
> 没有了，方便的话可以补充下文档 https://github.com/SonicCloudOrg/sonic-offical-website/edit/main/src/doc/doc-robot.md

好的 我明天写一下

2023-03-12 14:30 UTC, ZhouYixun commented
你好，可以将你的快递信息发送到 soniccloudorg@163.com 哦，我们会给您寄出一份小礼物