feat: 添加最长闲置时间获取、设置接口及其数据库初始化等
SonicCloudOrg/sonic-server pull request #344
Opened 2023-04-11 13:38 UTC by 844817946

> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [ ] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [ ] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [ ] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [ ] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### Description

2023-04-12 08:09 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/controller/ConfListController.java
> +        return new RespModel<>(RespEnum.HANDLE_OK);
```
List<Agents> agentsList = agentsService.findAgents();
        for (Agents agents : agentsList) {
            JSONObject result = new JSONObject();
            result.put("msg", "settings");
            result.put("inactiveTimeout", timeout);
            TransportWorker.send(agents.getId(), result);
        }
```

这段不需要，这段是配置要同步到Agent，你这个纯前端控制的，Agent不需要这样处理

只要save了就完事了

2023-04-12 08:11 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/config/SonicRunner.java
> +            confListService.save(ConfType.INACTIVE_DEBUG_TIMEOUT, "90", null);
默认时长还是设置成跟之前 480 一致，因为对于旧用户来说没看更新日志的话，用着用着突然退出会很懵。建议跟之前的一致，然后用户自己按需来后台配置

2023-04-12 08:11 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/controller/ConfListController.java
> +    @Operation(summary = "设置不活跃超时时间", description = "设置不活跃超时时间")
`不活跃` `无操作` `闲置` 其实都是同一个意思，但是你前后端太多种说法了，我建议统一改为 闲置

2023-04-12 08:12 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/transport/TransportServer.java
> +            auth.put("inactiveTimeout", confListService.searchByKey(ConfType.INACTIVE_DEBUG_TIMEOUT).getContent());
这个完全不需要，理由跟上面一样

2023-04-12 08:13 UTC, ZhouYixun requested changes
需要改动

2023-04-12 10:46 UTC, 844817946 commented
ok，后端我提交了，前端我明天提

2023-04-12 13:16 UTC, ZhouYixun commented
暂时没问题了，等你前端调整完合入

2023-04-13 13:16 UTC, ZhouYixun approved these changes
mg

2023-04-13 13:16 UTC, merged

2023-04-13 13:17 UTC, ZhouYixun commented
感谢你的贡献，可以将快递收发信息（包含真实姓名和手机号）、pr地址一同发送到 soniccloudorg@163.com 领取小礼品