fix:删除项目时，有三个关联表的记录未处理，存在脏数据
SonicCloudOrg/sonic-server pull request #352
Opened 2023-05-13 10:10 UTC by caofengbin

> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [ ] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [ ] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [ ] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [ ] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### Description

[删除步骤时，steps_elements表中的记录未同步删除，是有什么特殊的考虑吗？](https://sonic-cloud.wiki/d/2899-steps-elements)
社区之前讨论的一个问题，我这边整体梳理检查了下，目前项目中存在4个关联映射表：

> public_steps_steps
> steps_elements
> test_suites_test_cases
> test_suites_devices

public_steps_steps 我看已经处理了，另外三个我这次一起都改了，辛苦看看还有遗留没处理的关联表吗。

2023-05-13 10:33 UTC, caofengbin commented
删除单个测试套件时，也没清理test_suites_test_cases和test_suites_devices表，也补充上提交了

2023-05-13 11:46 UTC, ZhouYixun commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/services/impl/TestSuitesServiceImpl.java
>          return baseMapper.delete(new LambdaQueryWrapper<TestSuites>().eq(TestSuites::getProjectId, projectId)) > 0;
这块改成复用delete方法的吧

2023-05-13 11:47 UTC, ZhouYixun requested changes
不错，有个点微调一下

2023-05-13 11:56 UTC, caofengbin commented on sonic-server-controller/src/main/java/org/cloud/sonic/controller/services/impl/TestSuitesServiceImpl.java
>          return baseMapper.delete(new LambdaQueryWrapper<TestSuites>().eq(TestSuites::getProjectId, projectId)) > 0;
哦哦，确实，直接复用当前service下的delete单个测试套件的方法会精炼很多，而且查询的次数也会变少。

我改下

2023-05-13 12:09 UTC, caofengbin commented
> 不错，有个点微调一下

已修改，不过感觉`deleteByProjectId(int projectId)`方法返回bool的价值不大，目前也没什么用，我直接返回了查询到的套件个数，看看有优化的建议吗

2023-05-13 12:24 UTC, ZhouYixun commented
要么调整bool，要么改成返回每个子循环的bool结果吧，只要有false就为false

你现在的话如果没创建过测试套件，那就会删除失败了

2023-05-13 12:38 UTC, caofengbin commented
> 要么调整bool，要么改成返回每个子循环的bool结果吧，只要有false就为false
> 
> 你现在的话如果没创建过测试套件，那就会删除失败了

嗯我调整了下，辛苦再review看看哈

2023-05-14 04:44 UTC, ZhouYixun approved these changes
mg

2023-05-14 04:44 UTC, merged